Feature/osint 273 (maigret)
ICHEaccount/Ossistant pull request #154
Opened 2023-12-05 09:27 UTC by ahrufox

# [OSINT-273] maigret
## 🔑 Key Change 
- Maigret result with label, property, type, value

## 🖼️ Screenshots (if necessary)
![image]()

## 🙏 To Reviewers
🧑‍🤝‍🧑 @Teammate
- remark 1

2023-12-05 10:33 UTC, D7MeKz approved these changes
👍

2023-12-05 11:11 UTC, R3D1NM requested changes
SurfaceUser에 registered로 들어갑니다

2023-12-05 11:11 UTC, R3D1NM commented on server/osint/tools/lib/tool_maigret.py
> +            "property": "others",
registered임

2023-12-05 14:27 UTC, ahrufox commented on server/osint/tools/lib/tool_maigret.py
> +            "property": "others",
fixed

2023-12-06 03:35 UTC, R3D1NM approved these changes
👍

2023-12-06 04:14 UTC, merged